name=nikki.esp8266
version=1.0.0
author=Dev Nikki
maintainer=Dev Nikki <dev.nikki.build@gmail.com>
sentence=ESP8266 WebSocket client for nikki.build playground.
paragraph=This library provides a client library to connect with nikki.build playground.
category=Communication
url=https://github.com/nikki-build/nikki.esp8266
architectures=esp8266
depends=ArduinoJson,WebSockets